version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - "82:82"
    environment:
      - DATABASE_URL=mysql://dgd:dgd23825@db:3306/dgd_db
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 82
    depends_on:
      - db
      - elasticsearch

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - './services/frontend/node_modules:/app/node_modules'
    ports:
      - "8080:8080"

  db:
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=23825
      - MYSQL_DATABASE=dgd_db
      - MYSQL_USER=dgd
      - MYSQL_PASSWORD=dgd23825
    volumes:
      - type: bind
        source: ./services/mysql/data
        target: /var/lib/mysql
      - type: bind
        source: ./services/mysql/conf.d/
        target: /etc/mysql/conf.d/
      - type: bind
        source: ./services/mysql/my.cnf
        target: /etc/mysql/my.cnf
      - type: bind
        source: ./services/mysql/log
        target: /var/log/mysql

  elasticsearch:
    image: elasticsearch:7.17.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2G -Xmx4G"
    volumes:
      - /home/bwie/soft/elasticsearch/config/elasticsearch.yml:/services/elasticsearch/config/elasticsearch.yml
      - /home/bwie/soft/elasticsearch/data:/services/elasticsearch/data
      - /home/bwie/soft/elasticsearch/plugins:/services/elasticsearch/plugins

