version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - "82:82"
    environment:
      - DATABASE_URL=mysql://dgd:23825@db:3306/dgd_db
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 82
    depends_on:
      - db

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - "8080:8080"

  db:
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=23825
      - MYSQL_DATABASE=dgd_db
      - MYSQL_USER=dgd
      - MYSQL_PASSWORD=23825
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
